### ISSUE TITLE
mpl_toolbox issue

### ISSUE THREAD

**Issue by ccasella00** [jordandekraker/hippunfold_toolbox#2]
Hello,
I have been trying to install the toolbox but I keep on running into the following error:

Processing dependencies for hippunfold-toolbox==0.1.1
Searching for mpl_toolkits
Reading https://pypi.org/simple/mpl_toolkits/
Reading https://pypi.org/simple/mpl-toolkits/
Couldn't find index page for 'mpl_toolkits' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for mpl_toolkits
error: Could not find suitable distribution for Requirement.parse('mpl_toolkits')

I have trying updating matplotlib as well as trying different versions of Python. Do you have any suggestions please?

**Comment by jordandekraker** [comment]
Sorry about that, there is currently a bug in the pip installation. For now here is a temporary workaround:

```
import sys
sys.path.insert(1, '/<PATH_TO_YOUR_GIT_CLONE>/hippunfold_toolbox/hippunfold_toolbox')
import plotting
import utils
```

**Comment by ccasella00** [comment]
Apologies, I have another question.
I have been trying to run PALM on the data, e.g. to run a between group comparison between the myelin maps.
Usually when doing it with surface files (e.g. those outputted from the HCP pipeline) you need to provide a 4D file with the midthickness surfaces so that TFCE or any spatial statistics can be computed.
Normally I would do this like this:

left_average_midthickness_controls = []

for subject in control_IDs:
    left_average_midthickness_controls.append ('hippunfold/output/' + subject + '/surf/' + subject + '_hemi-L_space-unfolded_den-0p5mm_label-hipp_midthickness.surf.gii')
    L_midthickness_controls = ' '.join([str(item) for item in left_average_midthickness_controls])


cmd = 'wb_shortcuts -metric-concatenate hippunfold/midthickness/midthickness_4D_controls_left.shape.gii' + ' ' + L_midthickness_controls
print(cmd)
os.system(cmd)

However, when I try to do this with the hippunfold outputs I get the following error:


All data arrays (columns) in the file must have the same number of rows.  The first array (column) contains 14266 rows.  Array 2 contains 7262 rows.


I uderstand this is because the gifti files have vertices and faces, while this is probably not the case for the output of the HCP pipeline.

Do you have any advice on how I can work around this problem please?

Apologies if this isn't clear, happy to provide more info.

Thanks,
Chiara


------------------------------------------------------------------------

Chiara Casella, MSc, PhD


Research Associate

Department of Perinatal Imaging and Health

School of Biomedical Engineering & Imaging Sciences

King’s College London

1st Floor South Wing, St Thomas’ Hospital

London SE1 7EH

________________________________

**Comment by jordandekraker** [comment]
Though I've never done this before,  and can't test it right now, I suspect this could be done by first returning only vertex locations (ie. dropping the face data) using `wb_command -surface-coordinates-to-metric` before then applying `wb_shortcuts -metric-concatenate` on all subjects.

Let me know if that doesn't work and I'll see if I can come up with a solution on Monday.

Thanks for your interest in using HippUnfold!

**Comment by ccasella00** [comment]
Thanks a lot for your prompt response, it’s an amazing tool!




------------------------------------------------------------------------

Chiara Casella, MSc, PhD


Research Associate

Department of Perinatal Imaging and Health

School of Biomedical Engineering & Imaging Sciences

King’s College London

1st Floor South Wing, St Thomas’ Hospital

London SE1 7EH

________________________________
