### ISSUE TITLE
combine DG and CA4

### ISSUE THREAD

**Issue by HusBunia** [jordandekraker/hippunfold_toolbox#6]
Hi,
According to your answer in another issue [,](https://github.com/khanlab/hippunfold/issues/241#issue-1760210814). I tried to combine  DG and CA4 by using the label file from DeKraker25 atlas. I have a litter stupid question, the label in the atlas also have two seprate structrues, DG and CA. How can I combine them as a whole region? I just extract the mean value from the two regions as a substitution. 
Really appreciate for your advice ! 
Thanks.

**Comment by jordandekraker** [comment]
Sorry for the slow reply, I must have missed this earlier. 

In the DeKraker25 atlas CA4 and DG are already combined. If you still have more questions about this then reply here and I can go into more detail
